id: D55C60F0A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:49:57+00:00'
last_modified: '2022-05-26T10:56:29.975311+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9aef:
      image_group_id: I1PD95870
      title: འཕགས་པ་ལག་ན་རྡོ་རྗེ་གོས་སྔོན་པོ་ཅན་གྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག་ཐམས་ཅད་རྫོགས་པ།
      total_pages: 1853
      order: 25
      base_file: 9aef.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
